create tablespace CVID_PROD_DATA datafile 'c:\tmp\ORACLE_DIR\CVID_PROD_DATA' size 100M autoextend on;
create tablespace CVID_PROD_INDEX datafile 'c:\tmp\ORACLE_DIR\CVID_PROD_INDEX' size 100M autoextend on;

-- eliminate certain columns in a table
alter table "CVID_PROD"."PERMANENT_CVID" drop (HPI_ORG_ID, PROFESSIONAL_BODY_GROUP, PROFESSIONAL_BODY_REF);
alter table "CVID_PROD"."PERMANENT_CVID" drop (CPN, NHI_VALID, VACCINE_CODE, INDICATION, COMPLETION_STATUS, PROCESS_STATUS, PROCESS_MESSAGE, PAY_AMOUNT, DAY_RATE, AH_RATE, ACTIVE_PPD, IN_CMS, ACTIVE_ON_DOS,  PERORG_ACTIVE_ON_DOS, PERORG_IN_PERORG, PH_REGION, TIME_ZONE, AUDIT_TRAIL, INVOICE_NUMBER, FUNDER, CONTRACT_VERSION, CONTRACT_NAME, PU_CODE_DAY, PU_CODE_AH, FIN_SUPPLIER_SITE, GL_CODE_BH, GL_CODE_AH, EBS_GL_AH, EBS_GL_BH);
