ALTER USER steve IDENTIFIED BY foobar883;
ALTER USER SYS IDENTIFIED BY stevek883#;

SELECT value AS ORACLE_HOME
FROM v$parameter
WHERE name = 'oracle_home';

SHOW PARAMETER spfile;
SHOW PARAMETER REMOTE_LOGIN_PASSWORDFILE;
