ALTER SESSION SET CONTAINER = XEPDB1;
SELECT username
FROM dba_users
WHERE common = 'NO';
alter user steve2 identified by foobar883;
# this will create output you can then run
GRANT CREATE SESSION TO STEVE2;
SELECT 'GRANT SELECT, INSERT, UPDATE, DELETE, READ ON STEVE.' || table_name || ' TO STEVE2;'
FROM all_tables
WHERE owner = 'STEVE';

GRANT SELECT, INSERT, UPDATE, DELETE, READ ON STEVE.ALL_AGES TO STEVE2;
GRANT SELECT, INSERT, UPDATE, DELETE, READ ON STEVE.B9 TO STEVE2;
GRANT SELECT, INSERT, UPDATE, DELETE, READ ON STEVE.BARRY TO STEVE2;
GRANT SELECT, INSERT, UPDATE, DELETE, READ ON STEVE.JOINED_TABLE TO STEVE2;
GRANT SELECT, INSERT, UPDATE, DELETE, READ ON STEVE.NHI TO STEVE2;
